# Git
alias gs='git status '
alias gst='git stash'
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gp='git pull'
alias gpo='git push origin'
alias grm='git rebase master'
alias gri='git rebase -i'
alias gr='git rebase'
alias gl='git log'
alias gunt='git clean -f -X'